### ISSUE TITLE
g27 pedals issue since patch install

### ISSUE THREAD

**Issue by Khalogan** [CookiePLMonster/SilentPatchCMR3#13] opened 2024-05-29 15:05 UTC
I use a g27 and before the patch, everything worked perfectly.

the problem comes from the pedals, there's a problem
when I set them to default, i.e. each pedal assigned to a function, it doesn't work
in the configuration, it only detects “embreyage” in PDV2 and “accelerator” in speed, but the “brake” embreyage remains empty even if I activate the pedal.

and strangely enough, in the play sensitivity configuration, it detects them all...
speed in “axis y 1
brake in “rotation axis Z 1”.
and embreyage in “pdv 2”.

steering wheel settings on windows are default....

**Comment by CookiePLMonster** [comment] 2024-06-03 08:48
Duplicate of #12.

**Closed as not planned by CookiePLMonster** 2024-06-03 08:48 UTC
